Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Sub "tiki-${AWS::AccountId}-${AWS::Region}-dashboard"
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: error.html
