name: "Release"

on:
  workflow_dispatch:

env:
  AWS_REGION: "us-east-2"
  RELEASE_BUCKET: "tiki-024848454348-us-east-2-dashboard"

jobs:
  copy_files:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Assume OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_IDENTITY_ID }}:role/GitHubOidc
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - name: Assume Artifacts Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ARTIFACTS_ID }}:role/GitHubS3StaticRelease
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true
          role-chaining: true

      - name: Get Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          noVersionBumpBehavior: "silent"
          noNewCommitBehavior: "silent"

      - name: Copy Static Site
        run: aws s3 sync s3://tiki-artifacts-catalog/dashboard/${{ steps.semver.outputs.current }} s3://${{ env.RELEASE_BUCKET }} --recursive
